spring:
  application:
    name: account-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  cloud:
    consul:
      config:
        name: account-service
      port: 8500
      host: localhost
      discovery:
        prefer-ip-address: true
  datasource:
    username: root
    password: root
    url: jdbc:MySQL://localhost:3306/sck?&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 80
logging:
  level: info


