spring:
  application:
    name: account-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  cloud:
    consul:
      config:
        name: account-service
      port: 8500
      host: localhost
      discovery:
        prefer-ip-address: true
  datasource:
    username: root
    password: abcd1234
    url: jdbc:mysql://192.168.1.57:3306/sck?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver

server:
  port: 80
logging:
  level: info


